# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Randy Ridenour
tagline:             
description:         
url:                 http://randyridenour.net
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Randy Ridenour
  url:               https://twitter.com/randyridenour
  email:             rlridenour@gmail.com

# CSS
sass:
  sass_dir: _sass
  style: :compressed

# Plugins
plugins:
  [jekyll-paginate]

# Prose.io
prose:
  rooturl: '_posts'
  siteurl: "http://randyridenour.net"
  media: "images"
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "published"
        field:
          label: "published"
          element: "checkbox"
          value: "true"
      - name: "comments"
        field:
          label: "Comments"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Post Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Philosophy"
              value: "Philosophy"
            - name: "Religion"
              value: "Religion"
            - name: "Prayer"
              value: "Prayer"
            - name: "Technology"
              value: "Technology"
          
# Custom vars
version:             1.0.0
